language: java
jdk: oraclejdk8

script: mvn clean install -DskipTests

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "put custom osx code in here"    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "put custom linux code in here" ; fi

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9

# -Dgpg.skip to not sign installer with gpg, if omitted add a -Dgpg.passphrase=thephrase or use encrypted entry in settings.xml see http://maven.apache.org/plugins/maven-gpg-plugin/usage.html
script: mvn clean install -DskipTests -Dgpg.skip

notifications:
  slack:
    rooms:
      - secure: H82Q57T5nRNDfVnxzlWZ2WoeGt71oq2eJGHbqJ4wP2tIc8b02UO9bztPKFxbm9slMu0JjxZdJfnHSgNZKfPVXrTqwPYRVjKqm7m9TynIlkQabV+yCI/oRvy4Xi/Xj7/aPvZat4s/bxjrtw9KwVdpmqWvRNNSgiTqQ4teBJ1uQGs=
    on_success: change
    on_failure: always
