language: java

os:
  - linux
  - osx


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "put custom osx code in here"    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "put custom linux code in here" ; fi

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      before_install:
      - ./travis-download-maven.sh
      - export M2_HOME=$HOME/.binaries/apache-maven-3.3.9
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -Xmx32m --version
    - os: osx
      osx_image: xcode8
      before_install:
      - ./travis-download-maven.sh
      - export M2_HOME=$HOME/.binaries/apache-maven-3.3.9
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -Xmx32m --version

install:
  - git clone -b bisq_0.14.4.1 https://github.com/bitsquare/bitcoinj.git
  - cd bitcoinj
  - mvn clean install -DskipTests
  - git clone https://github.com/bitsquare/libdohj.git
  - cd libdohj
  - mvn clean install -DskipTests
  - git clone https://github.com/bitsquare/btcd-cli4j.git
  - cd btcd-cli4j
  - mvn clean install -DskipTests
  - cd ..

# -Dgpg.skip to not sign installer with gpg, if omitted add a -Dgpg.passphrase=thephrase or use encrypted entry in settings.xml see http://maven.apache.org/plugins/maven-gpg-plugin/usage.html
script: mvn clean install -DskipTests -Dgpg.skip

#notifications:
#  irc:
#    channels: chat.freenode.net#bisq
#    template:
#      - '%{message} (%{repository}#%{build_number}, %{duration})'
#      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
#      - '%{build_url}'
#    on_success: change
#    on_failure: always
#    use_notice: true
#    skip_join: true